import React from 'react';
import './styles/ProductView.css'
import chair1 from './img/Chair1.png';
import chair2 from './img/Chair2.png';
import chair3 from './img/Chair3.png';
import chair4 from './img/Chair4.png';
import chair5 from './img/Chair5.png';
import chair6 from './img/Chair6.png';
import table1 from './img/Table1.png';
import table2 from './img/Table2.png';
import table3 from './img/Table3.png';
import sofa1 from './img/Sofa1.png';
import sofa2 from './img/Sofa2.png';
import sofa3 from './img/Sofa3.png';
import sofa4 from './img/Sofa4.png';
import sofa5 from './img/Sofa5.png';
import sofa6 from './img/Sofa6.png';
import sofa7 from './img/Sofa7.png';

import { initializeApp } from "https://www.gstatic.com/firebasejs/9.4.0/firebase-app.js";
import { getDatabase, ref, onValue, push, update} from "https://www.gstatic.com/firebasejs/9.4.0/firebase-database.js";
import { getAuth} from "https://www.gstatic.com/firebasejs/9.4.0/firebase-auth.js";

// Firebase configuration
// For Firebase JS SDK v7.20.0 and later
const firebaseConfig = {
    apiKey: "AIzaSyDsfPr2HvfXQa7f5UP0wVE5Ctx7zzHspJg",
    authDomain: "modus-eac11.firebaseapp.com",
    projectId: "modus-eac11",
    storageBucket: "modus-eac11.appspot.com",
    messagingSenderId: "370786540996",
    appId: "1:370786540996:web:169cf51e66e678e1b1d891",
    measurementId: "G-0F4G8BD80F"
  };

  // Initialize Firebase
  const app = initializeApp(firebaseConfig);
  const databaseHolder = getDatabase(app);
  const auth = getAuth();

let prodObj = {
    "Chair1":{info:"Фотьойл Mira",text:"Фотьойл с модерен дизайн, удобна седалка, практични размери и здрава конструкция, подходящ за всяко пространство.", specText:"Цвят: розовТегло: 20 кг Гаранция: 2 години", pic:chair1, price:"Цена: 220 лв"},
    "Chair2":{info:"Стол Aros",text:"Стол с дизайн, отговарящ на модерните тенденции в декорацията, идеален за дома или офиса.", specText:"Цвят: бял Тегло: 5 кг Гаранция: 2 години", pic:chair2, price:"69 лв"},
    "Chair3":{info:"Стол Armada",text:"Стол с дизайн, отговарящ на последните тенденции в декорацията, идеален за дома или офиса.", specText:"Цвят: черен Тегло: 4.5 кг Гаранция: 2 години", pic:chair3, price:"59 лв"},
    "Chair4":{info:"Офис стол Fabri",text:"Офис стол с удобна и извита седалка с амортисьор за повдигане, спомагаща за поддържане на правилна и удобна позиция на тялото по време на работа. ", specText:"Цвят: черен Тегло: 15 кг Гаранция: 2 години", pic:chair4, price:"179 лв"},
    "Chair5":{info:"Стол Comfy Yellow",text:"Стол с модерен дизайн и здрава конструкция, подходящ за освежаване на Вашия балкон или градина.", specText:"Цвят: жълт Тегло: 10 кг Гаранция: 2 години", pic:chair5, price:"149 лв"},
    "Chair6":{info:"Стол Comfy White",text:"Стол с модерен дизайн и здрава конструкция, подходящ за освежаване на Вашия балкон или градина.", specText:"Цвят: бял Тегло: 12 кг Гаранция: 2 години", pic:chair6, price:"155 лв"},
    "Table1":{info:"Маса",text:"Описание", specText:"Цвят: черен Тегло: 4.5 кг Гаранция: 2 години", pic:table1, price:"149.99лв"},
    "Table2":{info:"Маса",text:"Описание", specText:"Цвят: черен Тегло: 4.5 кг Гаранция: 2 години", pic:table2, price:"199.99лв"},
    "Table3":{info:"Маса",text:"Описание", specText:"Цвят: черен Тегло: 4.5 кг Гаранция: 2 години", pic:table3, price:"29.99лв"},
    "Sofa1":{info:"Диван",text:"Описание", specText:"Цвят: черен Тегло: 4.5 кг Гаранция: 2 години", pic:sofa1, price:"309.99лв"},
    "Sofa2":{info:"Диван",text:"Описание", specText:"Цвят: черен Тегло: 4.5 кг Гаранция: 2 години", pic:sofa2, price:"400"},
    "Sofa3":{info:"Диван",text:"Описание", specText:"Цвят: черен Тегло: 4.5 кг Гаранция: 2 години", pic:sofa3, price:"999.99лв"},
    "Sofa4":{info:"Диван",text:"Описание", specText:"Цвят: черен Тегло: 4.5 кг Гаранция: 2 години", pic:sofa4, price:"1299.99лв"},
    "Sofa5":{info:"Диван",text:"Описание", specText:"Цвят: черен Тегло: 4.5 кг Гаранция: 2 години", pic:sofa5, price:"899.99лв"},
    "Sofa6":{info:"Диван",text:"Описание", specText:"Цвят: черен Тегло: 4.5 кг Гаранция: 2 години", pic:sofa6, price:"799.99лв"},
    "Sofa7":{info:"Диван",text:"Описание", specText:"Цвят: черен Тегло: 4.5 кг Гаранция: 2 години", pic:sofa7, price:"699.99лв"}
}

let userHolder;
auth.onAuthStateChanged((user) => {
    if (user) {
      // User is signed in, see docs for a list of available properties
      //getting user ref in order to reach user data in database
      userHolder = user;
      // ...
    } else {
      // User is signed out
      console.log("The user is signed off!");
    }
  });

function sendProductToDatabase(passedName,passedPic,passedPrice,database){
    const productRef = ref(database, 'productHolder/' + userHolder.uid + "-product");
    // Get the unique ID generated by push() by accessing its key
    const newPostKey = push(productRef).key;
    const updates = {};
    const productData = {
        name: passedName,
        pic: passedPic,
        id: newPostKey,
        from: userHolder.uid,
        price: passedPrice,
        };
        updates['productHolder/' + userHolder.uid + "-product/" + newPostKey] = productData;
        // Get the unique ID generated by push() by accessing its key
        alert("Продукта е добавен в количката!")
        return update(ref(database), updates);
}

function ProductView(){
    return(
        <div>
            <div className="row">
                <div className="column">
                <img className='show-container-item' src={prodObj[localStorage.getItem("ProdName")].pic}/>
                </div>
                <div className="column">
                    <h2 className='prod-Inf'>{prodObj[localStorage.getItem("ProdName")].info}</h2>
                    <p>{prodObj[localStorage.getItem("ProdName")].text}</p>
                    <h3 className='prod-Spec'>Спецификации:</h3>
                    <p>{prodObj[localStorage.getItem("ProdName")].specText}</p>
                    <p>{prodObj[localStorage.getItem("ProdName")].price}</p>
                    <button className="Send-btn" onClick={()=>sendProductToDatabase(prodObj[localStorage.getItem("ProdName")].info,
                    prodObj[localStorage.getItem("ProdName")].pic,
                    prodObj[localStorage.getItem("ProdName")].price,
                    databaseHolder)}>Добави в количка</button>
                </div>
            </div>
        </div>
    )
}

export default ProductView