import React from 'react';
import './styles/ProductView.css'

import { initializeApp } from "https://www.gstatic.com/firebasejs/9.4.0/firebase-app.js";
import { getDatabase, ref, push, update} from "https://www.gstatic.com/firebasejs/9.4.0/firebase-database.js";
import { getAuth} from "https://www.gstatic.com/firebasejs/9.4.0/firebase-auth.js";

import prodObj from './ProductObject';
// Firebase configuration
// For Firebase JS SDK v7.20.0 and later
const firebaseConfig = {
    apiKey: "AIzaSyDsfPr2HvfXQa7f5UP0wVE5Ctx7zzHspJg",
    authDomain: "modus-eac11.firebaseapp.com",
    projectId: "modus-eac11",
    storageBucket: "modus-eac11.appspot.com",
    messagingSenderId: "370786540996",
    appId: "1:370786540996:web:169cf51e66e678e1b1d891",
    measurementId: "G-0F4G8BD80F"
  };

  // Initialize Firebase
  const app = initializeApp(firebaseConfig);
  const databaseHolder = getDatabase(app);
  const auth = getAuth();

let userHolder;
let logged;
auth.onAuthStateChanged((user) => {
    if (user) {
      // User is signed in, see docs for a list of available properties
      //getting user ref in order to reach user data in database
      userHolder = user;
      logged = true;
      // ...
    } else {
      // User is signed out
      logged = false;
    }
  });

function sendProductToDatabase(passedName,passedPic,passedPrice,database){
  if(logged){
    const productRef = ref(database, 'productHolder/' + userHolder.uid + "-product");
    // Get the unique ID generated by push() by accessing its key
    const newPostKey = push(productRef).key;
    const updates = {};
    const productData = {
        name: passedName,
        pic: passedPic,
        id: newPostKey,
        from: userHolder.uid,
        price: passedPrice,
        };
        updates['productHolder/' + userHolder.uid + "-product/" + newPostKey] = productData;
        // Get the unique ID generated by push() by accessing its key
        alert("Продукта е добавен в количката!")
        return update(ref(database), updates);
    }else{
      alert("Моля влезте акаунта си за да правите покупки!")
    }
}

function ProductView(){
    return(
        <div>
            <div className="row">
                <div className="column">
                <img className='show-container-item' src={prodObj[localStorage.getItem("ProdName")].pic}/>
                </div>
                <div className="column">
                    <h2 className='prod-Inf'>{prodObj[localStorage.getItem("ProdName")].info}</h2>
                    <p>{prodObj[localStorage.getItem("ProdName")].text}</p>
                    <h3 className='prod-Spec'>Спецификации:</h3>
                    <p className='prod-Text'>{prodObj[localStorage.getItem("ProdName")].specText}</p>
                    <p>Цена: {prodObj[localStorage.getItem("ProdName")].price} лв</p>
                    <button className="Send-btn" onClick={()=>sendProductToDatabase(prodObj[localStorage.getItem("ProdName")].info,
                    prodObj[localStorage.getItem("ProdName")].pic,
                    prodObj[localStorage.getItem("ProdName")].price,
                    databaseHolder)}>Добави в количка</button>
                </div>
            </div>
        </div>
    )
}

export default ProductView